apiVersion: v2
name: sync-seat
description: Helm Umbrella Chart for Sync Seat Microservices Platform
type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Infrastructure
  - name: postgres
    version: 0.1.0
    repository: "file://charts/postgres"
    condition: postgres.enabled

  - name: redis
    version: 0.1.0
    repository: "file://charts/redis"
    condition: redis.enabled


  # Backend Microservices
  - name: booking
    version: 0.1.0
    repository: "file://charts/booking"
    condition: booking.enabled

  - name: mail
    version: 0.1.0
    repository: "file://charts/mail"
    condition: mail.enabled

  - name: homepage
    version: 0.1.0
    repository: "file://charts/homepage"
    condition: homepage.enabled

  - name: api-gateway
    version: 0.1.0
    repository: "file://charts/api-gateway"
    condition: api-gateway.enabled


  # Frontend
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
    condition: frontend.enabled
