# ==========================================================
# Sync Seat Umbrella Chart
# Global values shared across child charts
# ==========================================================

global:
  namespace: sync-seat

  imagePullPolicy: Always

  storageClass: ""

# ==========================================================
# Infrastructure
# ==========================================================

postgres:
  enabled: true

redis:
  enabled: true


# ==========================================================
# Backend Services
# ==========================================================

booking:
  enabled: true

mail:
  enabled: true

homepage:
  enabled: true

api-gateway:
  enabled: true


# ==========================================================
# Frontend
# ==========================================================

frontend:
  enabled: true


ingress:
  enabled: false

  className: gce

  annotations: {}

  hosts:
    - host: shop.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend
            port: 80