apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sync-seat
  namespace: argocd

spec:
  project: sync-seat

  source:
    repoURL: https://github.com/phanivarun05/sync-seat-gitops-eks.git
    targetRevision: main
    path: helm/syncseat

    helm:
      releaseName: sync-seat
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://172.18.0.2:6443
    namespace: sync-seat

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true